### ISSUE TITLE
Getting following error while running FastMM.m script with mcmc 'ON'

### ISSUE THREAD

**Issue by anilk991** [GonghuaLi/FastMM#2]
The following is the error:

Unrecognized function or variable 'N_samples'.
Error in FastMM (line 67)
    for i  = 1:N_samples_ 

It looks like N_samples_ has not been defined.

**Comment by GonghuaLi** [comment]
Thank you for your testing. 

The mcmc as you mentioned is just a pseudo function. 
To run mcmc, you need to compile the mcmc function locally using gcc with cplex, mkl  and matio library, such that:

gcc ./src/mcmc_cplex_mkl_prepared_null_v4.c -g -o mcmc_cplex_mkl_prepared_null -I/yourpath/cplex/include/ -I/yourpath/matio/include  -L/yourpath/cplex/lib/x86-64_linux/static_pic -L/home/ligh/programm/matio/lib -I/yourpath/linux/mkl/include   -L/yourpath/linux/compiler/lib/intel64_lin -/yourpath/linux/mkl/lib/intel64 -Wl,--no-as-needed -lmkl_intel_lp64 -lmkl_core -lmkl_intel_thread -liomp5 -lpthread -lm -ldl -DMKL_LP64 -m64  -lmatio -lcplex -O3

After success, you may using the following function as following:

outmodel = FastMCMC(outmodel,2000,1000,outfilepath,'needNullS');

Hope this message will help you.

**Comment by anilk991** [comment]
Thank you.
